
spring:
  jpa:
    show-sql: true
  application:
    name: POC-DB-aisolation-levels
  datasource:
    password: poc
    username: poc
    url: jdbc:mariadb://localhost:3306/poc?useSSL=false
server:
  port: 9001
